docs: Clarify behaviour of multiple matchers of the same type
caddyserver/website pull request #102
Opened 2020-11-01 21:19 UTC by francislavoie

Followup to https://github.com/caddyserver/caddy/pull/3832 and https://github.com/caddyserver/caddy/pull/3839 to clarify how each matchers are merged, if possible.

I'm not perfectly satisfied with the wording, so feel free to suggest revisions 👍

2020-11-03 17:53 UTC, mholt requested changes
Thanks! I did find the phrasing a little confusing/awkward on a lot of these, so I made some suggestions to simplify them. Let me know what you think.

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +For some matchers that accept multiple values, those values are OR'ed; i.e. one must match in order for the matcher to match. See the docs for each matcher for details on how they are merged.
```suggestion
Multiple matchers are combined using boolean algebra (AND/OR), as described by each section below.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +If used multiple times in the same named matcher, matchers with the same header field will be merged, which will OR the values of each.
I think this is a wee bit confusing... how about:

```suggestion
Different header fields within the same set are AND-ed. Multiple values per field are OR-ed.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +There can only be multiple `header_regexp` matchers per named matcher, but only one per field. Each field will be AND'ed.
The rest of these also read a little awkward to me, what if we try this:

```suggestion
Only one regular expression is supported per header field. Multiple different fields will be AND-ed.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +There can be multiple `host` matchers per named matcher, merging them. The hosts will be OR'ed.
```suggestion
Multiple `host` matchers will be OR'ed together.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +There can be multiple `method` matchers per named matcher, merging them. The verbs will be OR'ed.
```suggestion
Multiple `method` matchers will be OR'ed together.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +There can be multiple `path` matchers per named matcher, merging them. The paths will be OR'ed.
```suggestion
Multiple `path` matchers will be OR'ed together.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +By query string parameters. Should be a sequence of `key=value` pair. Keys are matched exactly, case-sensitively. Values can contain placeholders. Values are matched exactly, but also support `*` to
```suggestion
By query string parameters. Should be a sequence of `key=value` pairs. Keys are matched exactly, case-sensitively. Values can contain placeholders. Values are matched exactly, but also support `*` to match any value.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +There can be multiple `query` matchers per named matcher, and pairs with the same keys will be merged together, which will OR the values of each.
```suggestion
There can be multiple `query` matchers per named matcher, and pairs with the same keys will be OR'ed together.
```

2020-11-03 17:53 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +There can be multiple `remote_ip` matchers per named matcher, merging them. The addresses will be OR'ed.
```suggestion
Multiple `remote_ip` matchers will be OR'ed together.
```

2020-11-03 18:08 UTC, francislavoie commented on src/docs/markdown/caddyfile/matchers.md
> +For some matchers that accept multiple values, those values are OR'ed; i.e. one must match in order for the matcher to match. See the docs for each matcher for details on how they are merged.
I think 
```suggestion
Multiple matchers of the same type are combined using boolean algebra (AND/OR), as described by each section below.
```

i.e. + "of the same type"

2020-11-03 18:10 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +For some matchers that accept multiple values, those values are OR'ed; i.e. one must match in order for the matcher to match. See the docs for each matcher for details on how they are merged.
Even different matchers are combined using AND logic though.

2020-11-03 18:15 UTC, francislavoie commented on src/docs/markdown/caddyfile/matchers.md
> +For some matchers that accept multiple values, those values are OR'ed; i.e. one must match in order for the matcher to match. See the docs for each matcher for details on how they are merged.
True. I think we should separate those ideas then. It should be clear that matchers of a different type will always be ANDed but matchers of the same type may be AND or OR depending.

2020-11-24 04:54 UTC, francislavoie commented on src/docs/markdown/caddyfile/matchers.md
> +For some matchers that accept multiple values, those values are OR'ed; i.e. one must match in order for the matcher to match. See the docs for each matcher for details on how they are merged.
Updated, went with:

```
Multiple matchers of the same type (e.g. multiple `path` matchers in the same set) may be combined using boolean algebra (AND/OR), as described in their respective sections below.
```

I think that's probably okay.

2020-11-24 21:29 UTC, mholt requested changes
A couple minor changes for consistency and clarity. Almost there!

2020-11-24 21:29 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +Only one regular expression is supported per header field. Multiple different fields will be AND-ed.
```suggestion
Only one regular expression is supported per header field. Multiple different fields will be AND'ed.
```

2020-11-24 21:29 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +Multiple matchers of the same type (e.g. multiple `path` matchers in the same set) may be combined using boolean algebra (AND/OR), as described in their respective sections below.
```suggestion
Multiple matchers of the same type may be combined (e.g. multiple `path` matchers in the same set) using boolean algebra (AND/OR), as described in their respective sections below.
```

Just to make it clearer that we're not talking about combining multiple sets, but multiple matchers within a set.

2020-11-24 21:29 UTC, mholt commented on src/docs/markdown/caddyfile/matchers.md
> +Different header fields within the same set are AND-ed. Multiple values per field are OR-ed.
```suggestion
Different header fields within the same set are AND-ed. Multiple values per field are OR'ed.
```

2020-11-24 21:44 UTC, mholt approved these changes

2020-11-24 21:44 UTC, merged