Update command-line.md
caddyserver/website pull request #174
Opened 2021-06-21 15:51 UTC by basilhendroff

Add build-info and upgrade subcommands to the summary

2021-06-21 17:01 UTC, mholt approved these changes
Thank you!

2021-06-21 17:01 UTC, Mohammed90 commented on src/docs/markdown/command-line.md
> +- **[caddy unpgrade](#caddy-upgrade)**
```suggestion
- **[caddy upgrade](#caddy-upgrade)**
```

2021-06-21 17:01 UTC, mholt requested changes
Actually pls fix typo :)

2021-06-21 17:01 UTC, mholt commented on src/docs/markdown/command-line.md
> +- **[caddy unpgrade](#caddy-upgrade)**
```suggestion
- **[caddy upgrade](#caddy-upgrade)**
```

2021-06-30 05:49 UTC, francislavoie approved these changes

2021-06-30 05:49 UTC, merged