docs: Updates for Caddy v2.4.4
caddyserver/website pull request #189
Opened 2021-08-26 03:55 UTC by francislavoie

2021-08-26 04:01 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/reverse_proxy.md
> -Since these header fields are only de-facto standards, Caddy may stop setting them implicitly in the future if the standardized [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/F
I'm removing this, because frankly, it's confusing. The docs shouldn't speculate about the future, it should just talk about what Caddy does _now_. I think it's very unlikely we'll ever remove `X-Forwarded-For`, because pretty much _everything_ uses those. There really doesn't seem to be any industry appetite for moving to `Forwarded` (it's a more complicated format to parse, kinda does too much).

2021-08-26 04:01 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/reverse_proxy.md
>  }
I reorganized these to try to help clarify the actually usecase where `header_up Host {upstream_hostport}` is most commonly used. This is probably a bit too wordy though, I think I should move some of this copy to the `Headers` section above. 🤔

2021-08-26 04:01 UTC, francislavoie commented on src/docs/markdown/logging.md
> +	"duration": 0.000014711,
The logs haven't used `"latency"` for a very long time now, it's been `"duration"`. Was a bit misleading.

2021-08-26 04:01 UTC, francislavoie commented on src/download.html
> +							<option value="windows-arm64">Windows arm64</option>
I think this is ready to go along with v2.4.4. I haven't tested the cross-compile with `xcaddy` yet, if you want to try that on the build server as a sanity check, that'd be great

2021-08-26 17:01 UTC, mholt requested changes
Thanks for beating me to it. Mostly LGTM. I agree the part about the `header_up Host` change is still a bit confusing though... hmm.

2021-08-26 17:01 UTC, mholt commented on src/docs/markdown/caddyfile/directives/file_server.md
> +- **disable_canonical_uris** disables the default behaviour of redirecting to add a trailing slash if the request path is a directory, or remove the trailing slash if the request path is a file. Note
Canonicalization doesn't happen if the _end_ of a filename underwent an internal rewrite, right?

2021-08-26 17:01 UTC, mholt commented on src/docs/markdown/caddyfile/directives/reverse_proxy.md
> -Since these header fields are only de-facto standards, Caddy may stop setting them implicitly in the future if the standardized [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/F
Have multiple users been confused by this?

I don't feel strongly either way, just wondering.

2021-08-26 17:01 UTC, mholt commented on src/docs/markdown/command-line.md
> +  Upgrades Caddy to the latest release, with additional plugins added
Hmm, didn't we make it so that add-package and remove-package don't change/upgrade the Caddy version?

2021-08-26 17:01 UTC, mholt commented on src/docs/markdown/caddyfile/directives/reverse_proxy.md
> +- **flush_interval** is a [duration value](/docs/conventions#durations) that adjusts how often Caddy should flush the response buffer to the client. By default, no periodic flushing is done. A negati
"no periodic flushing is done" and "writes are flushed to the client immediately" are different or the same? (We should try to be clear about this in the docs.) In addition, I might also suggest putting the default part at the end.
```

2021-08-26 17:08 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/file_server.md
> +- **disable_canonical_uris** disables the default behaviour of redirecting to add a trailing slash if the request path is a directory, or remove the trailing slash if the request path is a file. Note
The wording is taken pretty much verbatim from the godoc, so :man_shrugging: I didn't review the implementation

2021-08-26 17:09 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/file_server.md
> +- **disable_canonical_uris** disables the default behaviour of redirecting to add a trailing slash if the request path is a directory, or remove the trailing slash if the request path is a file. Note
You wrote it here:

https://github.com/caddyserver/caddy/commit/191dc86f9e40c12517a133cf2181631c9adec791

2021-08-26 17:11 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/reverse_proxy.md
> -Since these header fields are only de-facto standards, Caddy may stop setting them implicitly in the future if the standardized [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/F
Yeah there were some users that asked "I shouldn't rely on this because it might go away later". I didn't dig on the forum to find an example, I just read it again while going through and found it misleading. It's not really valid to mention this because it's not actually deprecated or whatever, and we don't actually have any plans to change this.

2021-08-26 17:12 UTC, francislavoie commented on src/docs/markdown/command-line.md
> +  Upgrades Caddy to the latest release, with additional plugins added
I don't think so? Didn't read to me like that was the case in the code. Could you check?

2021-08-26 17:15 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/reverse_proxy.md
> +- **flush_interval** is a [duration value](/docs/conventions#durations) that adjusts how often Caddy should flush the response buffer to the client. By default, no periodic flushing is done. A negati
I essentially copied the wording from stdlib when I did that syncing PR :thinking: 

I kept the wording as close as possible to the godoc here.

```go
	// Adjusts how often to flush the response buffer. By default,
	// no periodic flushing is done. A negative value disables
	// response buffering, and flushes immediately after each
	// write to the client. This option is ignored when the upstream's
	// response is recognized as a streaming response, or if its
	// content length is -1; for such responses, writes are flushed
	// to the client immediately.
	FlushInterval caddy.Duration `json:"flush_interval,omitempty"`
```

2021-08-26 19:39 UTC, mholt commented on src/docs/markdown/caddyfile/directives/file_server.md
> +- **disable_canonical_uris** disables the default behaviour of redirecting to add a trailing slash if the request path is a directory, or remove the trailing slash if the request path is a file. Note
Right, but crucially, canonicalization can still happen if there's a rewrite: just not on the end of the path.

2021-08-26 19:44 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/file_server.md
> +- **disable_canonical_uris** disables the default behaviour of redirecting to add a trailing slash if the request path is a directory, or remove the trailing slash if the request path is a file. Note
> Note that by default, canonicalization does not happen if the filename was underwent an internal rewrite

It does say as much. How would you write it otherwise (aside from the grammatical error that I just noticed lmao)?

2021-08-26 20:21 UTC, francislavoie commented on src/docs/markdown/caddyfile/directives/file_server.md
> +- **disable_canonical_uris** disables the default behaviour of redirecting to add a trailing slash if the request path is a directory, or remove the trailing slash if the request path is a file. Note
I adjusted the wording.

2021-08-31 17:38 UTC, mholt commented on src/docs/markdown/command-line.md
> +  Upgrades Caddy to the latest release, with additional plugins added
Hmm I guess you're right. Before too long, I'd like to make it so that add-package and remove-package don't change the current Caddy version.

2021-08-31 17:38 UTC, mholt approved these changes
Thank you for the diligence, Francis! Makes things much easier.

2021-08-31 17:39 UTC, merged