Give a tip about not forgetting @ in curl command.
caddyserver/website pull request #19
Opened 2020-04-05 15:21 UTC by tobya

I'm running through the tutorial and and noteing things that give me a bit of trouble.

2020-04-06 00:58 UTC, mholt commented
Thanks Toby! Most people copy+paste examples/instructions. Were you typing it out manually?

2020-04-06 06:31 UTC, tobya commented
Yes,

I remember looking at it and thinking 'I'm sure that @ is important' then
not typing it.

Toby

On Mon, 6 Apr 2020 at 01:58, Matt Holt <notifications@github.com> wrote:

> Thanks Toby! Most people copy+paste examples/instructions. Were you typing
> it out manually?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/caddyserver/website/pull/19#issuecomment-609516399>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACPO7X4CZN5AIDRJNS7FZTRLESKTANCNFSM4MBACNJA>
> .
>

2020-04-06 21:19 UTC, mholt requested changes
Just a few matters of cleanup.

2020-04-06 21:19 UTC, mholt commented on src/docs/markdown/api-tutorial.md
> +
Extra lines? Can remove these, please :)

2020-04-06 21:19 UTC, mholt commented on src/docs/markdown/api-tutorial.md
> +	Make sure you dont forget the @ in front of your filename, this tells curl you are sending a file.
```suggestion
	Make sure you don't forget the @ in front of your filename; this tells curl you are sending a file.
```

2020-04-07 13:15 UTC, mholt approved these changes
Thanks Toby

2020-04-07 13:15 UTC, merged