docs: Clarify Caddyfile address separators
caddyserver/website pull request #61
Opened 2020-07-03 09:28 UTC by francislavoie

See https://github.com/caddyserver/caddy/issues/3545

2020-07-03 09:39 UTC, CaselIT approved these changes
Thanks, the docs are clearer now

2020-07-03 23:06 UTC, mholt requested changes
Thanks for the contribution, but I think some refinements need to be made.

2020-07-03 23:06 UTC, mholt commented on src/docs/markdown/caddyfile/concepts.md
> +If multiple sites share the same definition, you can list all of them together, separated by spaces or commas:
This is not entirely clear, since you always need spaces, you cannot separate them with commas.

2020-07-03 23:06 UTC, mholt commented on src/docs/markdown/caddyfile/concepts.md
> +To specify multiple addresses on separate lines, use commas to indicate continuation:
To be clearer, commas are required if using newlines between addresses.

2020-11-24 22:32 UTC, mholt commented
Closing due to inactivity

2020-11-24 22:32 UTC, closed without merging